export interface GalleryItem {
  slug: string;
  title: string;
  coverImage: string;
  images: string[];
}

export const galleryItems: GalleryItem[] = [
  {
    slug: "annual-day",
    title: "Annual Day",
    coverImage: "/images/gallery/annual-day/1.jpg",
    images: [
    "/images/gallery/annual-day/1.jpg",
    "/images/gallery/annual-day/2.jpg",
    "/images/gallery/annual-day/3.jpg",
    "/images/gallery/annual-day/4.jpg",
    "/images/gallery/annual-day/5.jpg",
    "/images/gallery/annual-day/6.jpg",
    "/images/gallery/annual-day/7.jpg",
    "/images/gallery/annual-day/8.jpg",
    "/images/gallery/annual-day/9.jpg",
    "/images/gallery/annual-day/10.jpg",
    "/images/gallery/annual-day/11.jpg",
    "/images/gallery/annual-day/12.jpg",
    "/images/gallery/annual-day/13.jpg",
    "/images/gallery/annual-day/14.jpg",
    "/images/gallery/annual-day/15.jpg",
    "/images/gallery/annual-day/16.jpg",
    "/images/gallery/annual-day/17.jpg",
    "/images/gallery/annual-day/18.jpg",
    "/images/gallery/annual-day/19.jpg",
    "/images/gallery/annual-day/20.jpg",
    "/images/gallery/annual-day/21.jpg",
    "/images/gallery/annual-day/22.jpg",
    "/images/gallery/annual-day/23.jpg"
],
  },
  {
    slug: "celebrations",
    title: "Celebrations",
    coverImage: "/images/gallery/celebrations/1.jpg",
    images: [
    "/images/gallery/celebrations/1.jpg",
    "/images/gallery/celebrations/2.jpg",
    "/images/gallery/celebrations/3.jpg",
    "/images/gallery/celebrations/4.jpg",
    "/images/gallery/celebrations/5.jpg",
    "/images/gallery/celebrations/6.jpg",
    "/images/gallery/celebrations/7.jpg",
    "/images/gallery/celebrations/8.jpg",
    "/images/gallery/celebrations/9.jpg",
    "/images/gallery/celebrations/10.jpg",
    "/images/gallery/celebrations/11.jpg",
    "/images/gallery/celebrations/12.jpg",
    "/images/gallery/celebrations/13.jpg",
    "/images/gallery/celebrations/14.jpg",
    "/images/gallery/celebrations/15.jpg",
    "/images/gallery/celebrations/16.jpg",
    "/images/gallery/celebrations/17.jpg",
    "/images/gallery/celebrations/18.jpg",
    "/images/gallery/celebrations/19.jpg",
    "/images/gallery/celebrations/20.jpg",
    "/images/gallery/celebrations/21.jpg",
    "/images/gallery/celebrations/22.jpg",
    "/images/gallery/celebrations/23.jpg",
    "/images/gallery/celebrations/24.jpg",
    "/images/gallery/celebrations/25.jpg",
    "/images/gallery/celebrations/26.jpg",
    "/images/gallery/celebrations/27.jpg",
    "/images/gallery/celebrations/28.jpg",
    "/images/gallery/celebrations/29.jpg",
    "/images/gallery/celebrations/30.jpg"
],
  },
  {
    slug: "centre-based",
    title: "Centre Based",
    coverImage: "/images/gallery/centre-based/1.jpg",
    images: [
    "/images/gallery/centre-based/1.jpg",
    "/images/gallery/centre-based/2.jpg",
    "/images/gallery/centre-based/3.jpg",
    "/images/gallery/centre-based/4.jpg",
    "/images/gallery/centre-based/5.jpg",
    "/images/gallery/centre-based/6.jpg",
    "/images/gallery/centre-based/7.jpg",
    "/images/gallery/centre-based/8.jpg",
    "/images/gallery/centre-based/9.jpg",
    "/images/gallery/centre-based/10.jpg",
    "/images/gallery/centre-based/11.jpg"
],
  },
  {
    slug: "activities",
    title: "Activities",
    coverImage: "/images/gallery/activities/1.jpg",
    images: [
    "/images/gallery/activities/1.jpg",
    "/images/gallery/activities/2.jpg",
    "/images/gallery/activities/3.jpg",
    "/images/gallery/activities/4.jpg",
    "/images/gallery/activities/5.jpg",
    "/images/gallery/activities/6.jpg",
    "/images/gallery/activities/7.jpg",
    "/images/gallery/activities/8.jpg",
    "/images/gallery/activities/9.jpg",
    "/images/gallery/activities/10.jpg",
    "/images/gallery/activities/11.jpg",
    "/images/gallery/activities/12.jpg",
    "/images/gallery/activities/13.jpg",
    "/images/gallery/activities/14.jpg",
    "/images/gallery/activities/15.jpg",
    "/images/gallery/activities/16.jpg",
    "/images/gallery/activities/17.jpg",
    "/images/gallery/activities/18.jpg"
],
  },
  {
    slug: "childrens-day",
    title: "Children's Day",
    coverImage: "/images/gallery/childrens-day/1.jpg",
    images: [
    "/images/gallery/childrens-day/1.jpg",
    "/images/gallery/childrens-day/2.jpg",
    "/images/gallery/childrens-day/3.jpg",
    "/images/gallery/childrens-day/4.jpg",
    "/images/gallery/childrens-day/5.jpg",
    "/images/gallery/childrens-day/6.jpg",
    "/images/gallery/childrens-day/7.jpg",
    "/images/gallery/childrens-day/8.jpg",
    "/images/gallery/childrens-day/9.jpg"
],
  },
  {
    slug: "christmas-day",
    title: "Christmas Day",
    coverImage: "/images/gallery/christmas-day/1.jpg",
    images: [
    "/images/gallery/christmas-day/1.jpg",
    "/images/gallery/christmas-day/2.jpg",
    "/images/gallery/christmas-day/3.jpg",
    "/images/gallery/christmas-day/4.jpg",
    "/images/gallery/christmas-day/5.jpg",
    "/images/gallery/christmas-day/6.jpg",
    "/images/gallery/christmas-day/7.jpg",
    "/images/gallery/christmas-day/8.jpg",
    "/images/gallery/christmas-day/9.jpg",
    "/images/gallery/christmas-day/10.jpg",
    "/images/gallery/christmas-day/11.jpg",
    "/images/gallery/christmas-day/12.jpg",
    "/images/gallery/christmas-day/13.jpg",
    "/images/gallery/christmas-day/14.jpg"
],
  },
  {
    slug: "pink-day",
    title: "Pink Day",
    coverImage: "/images/gallery/pink-day/1.jpg",
    images: [
    "/images/gallery/pink-day/1.jpg",
    "/images/gallery/pink-day/2.jpg",
    "/images/gallery/pink-day/3.jpg",
    "/images/gallery/pink-day/4.jpg",
    "/images/gallery/pink-day/5.jpg"
],
  },
  {
    slug: "purple-day",
    title: "Purple Day",
    coverImage: "/images/gallery/purple-day/1.jpg",
    images: [
    "/images/gallery/purple-day/1.jpg",
    "/images/gallery/purple-day/2.jpg",
    "/images/gallery/purple-day/3.jpg",
    "/images/gallery/purple-day/4.jpg",
    "/images/gallery/purple-day/5.jpg",
    "/images/gallery/purple-day/6.jpg",
    "/images/gallery/purple-day/7.jpg",
    "/images/gallery/purple-day/8.jpg",
    "/images/gallery/purple-day/9.jpg",
    "/images/gallery/purple-day/10.jpg",
    "/images/gallery/purple-day/11.jpg"
],
  },
  {
    slug: "republic-day",
    title: "Republic Day",
    coverImage: "/images/gallery/republic-day/1.jpg",
    images: [
    "/images/gallery/republic-day/1.jpg",
    "/images/gallery/republic-day/2.jpg",
    "/images/gallery/republic-day/3.jpg",
    "/images/gallery/republic-day/4.jpg",
    "/images/gallery/republic-day/5.jpg",
    "/images/gallery/republic-day/6.jpg",
    "/images/gallery/republic-day/7.jpg",
    "/images/gallery/republic-day/8.jpg",
    "/images/gallery/republic-day/9.jpg",
    "/images/gallery/republic-day/10.jpg",
    "/images/gallery/republic-day/11.jpg",
    "/images/gallery/republic-day/12.jpg",
    "/images/gallery/republic-day/13.jpg"
],
  },
  {
    slug: "bullock-cart-ride",
    title: "Bullock Cart Ride",
    coverImage: "/images/gallery/bullock-cart-ride/1.jpg",
    images: [
    "/images/gallery/bullock-cart-ride/1.jpg",
    "/images/gallery/bullock-cart-ride/2.jpg",
    "/images/gallery/bullock-cart-ride/3.jpg",
    "/images/gallery/bullock-cart-ride/4.jpg",
    "/images/gallery/bullock-cart-ride/5.jpg",
    "/images/gallery/bullock-cart-ride/6.jpg",
    "/images/gallery/bullock-cart-ride/7.jpg",
    "/images/gallery/bullock-cart-ride/8.jpg",
    "/images/gallery/bullock-cart-ride/9.jpg",
    "/images/gallery/bullock-cart-ride/10.jpg",
    "/images/gallery/bullock-cart-ride/11.jpg",
    "/images/gallery/bullock-cart-ride/12.jpg",
    "/images/gallery/bullock-cart-ride/13.jpg",
    "/images/gallery/bullock-cart-ride/14.jpg",
    "/images/gallery/bullock-cart-ride/15.jpg",
    "/images/gallery/bullock-cart-ride/16.jpg"
],
  },
];
